
java_library(
    name = "binary_tree_level_order_traversal",
    srcs = glob(["*.java"]),
    deps = ["//src/main/java/me/luangong/leetcode/common/binary_tree"],
    visibility = [
        "//src/test/java/me/luangong/leetcode/solutions/binary_tree_level_order_traversal:__pkg__",
    ],
)
