package(default_visibility = ["//visibility:public"])

java_library(
    name = "binary_search_tree_iterator",
    srcs = glob(["*.java"]),
    deps = ["//src/main/java/com/luangong/leetcode/common/binarytree"],
)
