# https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven and Bazel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build and test with Maven
        run: ./mvnw --batch-mode test

      - name: Build and test with Bazel
        run: bazelisk test --config=ci //...
